name: Javier
favicon: null
layout_spectrum: 0.943823805777356
typography_spectrum: 0.06726230517961085
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.7610636041499674
  lightness: 0.81754046282731
  saturation: 0.6592437876388431
  rhythmicContrast: 0.3366212493274361
purpose: []
