name: Javier
favicon: null
layout_spectrum: 0.27642
typography_spectrum: 1
title: Javier.SG
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d2d2d'
    - '#f7f7f7'
    - '#929292'
    - '#d5d5d5'
    - '#6a6a6a'
  brandStrength: 0.625
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
